### ISSUE TITLE
Räume regeln

### ISSUE THREAD

**Issue by TheHolyHawk** [TheHolyHawk/furry-cake#2]
Beim erstellen einer neuen Stunde wird der Raum nicht gespeichert, während bei bearbeiten eines Raumes weiterhin die Möglichkeit besteht Kommata zu nutzen, was wieder zum crash führt.

![giphy 1](https://user-images.githubusercontent.com/29118089/34957214-f616a628-fa2c-11e7-8d33-cc2db99506f8.gif)
 
@justus11 guck mal ob deine version auf der festplatte noch geht, was das erstellen betrifft, wenn ja hau die mal wieder rein, dann habe ich das nämlich später verschlimmbessert, irgendwann ging's ja mal...

**Comment by TheHolyHawk** [comment]
Habe nur neuenRaum verbessert, bearbeiten ist immer noch unsicher und löschen von Montags der ersten geht nicht so richtig

**Comment by Call-Paul** [comment]
Also habe jetzt bearbeiten sicher gemacht und das mit montags ersten beiden geht bei mir. Aktualisiere deine Version auf dem Handy mal mit dem neusten Stand und probiers dann nochmal. Wenn s geht diesen Fall schließen sodassich bescheid weiß. danke

**Comment by TheHolyHawk** [comment]
Räume funktionieren wie sie sollen, löschen mache ich ein neues Problem zu... sieht dann wie fortschritt aus
![giphy 2](https://user-images.githubusercontent.com/29118089/34991612-8f42b826-faca-11e7-8be9-72fbed4fb1d8.gif)
