### ISSUE TITLE
Montag erste Stunde löschen

### ISSUE THREAD

**Issue by TheHolyHawk** [TheHolyHawk/furry-cake#4]
Klappt nicht, Details folgen wenn ich Zeit habe

![giphy 3](https://user-images.githubusercontent.com/29118089/34991742-f9d82f40-faca-11e7-81a7-f8b0cb196bfe.gif)

**Comment by Call-Paul** [comment]
hä das ist so komisch bei mir funktioniert das

**Comment by TheHolyHawk** [comment]
Offenbar bei mir auch...?

**Comment by Call-Paul** [comment]
ja dann geht's ja jetzt
