### ISSUE TITLE
Montag erste Stunde Tim

### ISSUE THREAD

**Issue by TheHolyHawk** [TheHolyHawk/furry-cake#5]
Die erste Stunde montags lässt sich bei Tim nicht löschen sondern taucht bei jedem neustart wieder auf. Allelöschen() greift trotzdem und kann die Stunde entfernen. Bei Paul besteht kein Problem.

**Comment by TheHolyHawk** [comment]
Löschen der ersten Stunde Montags funktioniert wieder ohne ersichtlichen Grund oder tatsächliche Änderung im Code... Ich werde noch gucken ob das Problem wieder auftritt, ansonsten scheint es ohne Arbeit gelöst zu sein.
![giphy 4](https://user-images.githubusercontent.com/29118089/35484742-8dddebac-0454-11e8-88e7-ed2687f6ea55.gif)

**Comment by Call-Paul** [comment]
Damit wird das geschlossen.
