### ISSUE TITLE
finish() killt nicht nur das Email Fenster

### ISSUE THREAD

**Issue by TheHolyHawk** [TheHolyHawk/furry-cake#9]
Beim senden der App wird finish() aufgerufen um zur MainActivity zurück zu kommen, das funktioniert auch, aber nach zwei Sekunden crasht die App vollständig. in diesen zwei Sekunden funktioniert jedoch alles wie es sollte.

Hallo Tim,
beim Ablaufen der App in Android Studio unten die Logcat bzw. das Android Terminal öffnen. Dort müsste neben einigen anderen Meldungen des Device dann zu sehen sein, aus welchem Grund die App crashed. Dann versuchen diese Fehlermeldung zu interpretieren; )

**Comment by Call-Paul** [comment]
Hab das Probelm gefixt.
